-- Create the table anew
CREATE TABLE IF NOT EXISTS bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url text,
  description text,
  rating NUMERIC
  );

insert into bookmarks (title, url, description, rating)
values
  ('AOL', 'https://www.aol.com', 'Think outside the classroom', '5'),
  ('Thinkful', 'https://www.thinkful.com','Think outside the classroom', '5'),
  ('Google', 'http://www.google.com', 'where we find everything else', '4'),
  ('MDN', 'http://www.developer.mozilla.org', 'the only place to find web documentation', '5'),
  ('Yahoo', 'http://www.yahoo.com', 'old website', '3'),
  ('Facebook', 'http://www.facebook.com', 'we are watching you', '2'),
  ('Twitter', 'http://www.twitter.com', 'i still need to get an account', '3'),
  ('Insta', 'http://wwww.instagram.com', 'not this one either', '2');

  